<a href="https://colab.research.google.com/github/Sahilamin219/Taxi-ai/blob/main/Taxi_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gym

In [ ]:
# import
import numpy as np
import gym
import random

In [ ]:
env = gym.make('Taxi-v3')

In [ ]:
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [ ]:
# Create Table
grid = env.observation_space.n
action = env.action_space.n
print(grid, action)

500 6


In [ ]:
Q=np.zeros((grid,action))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# hyper perameter
Total_episodes = 25000
Max_steps=200
learning_rate=0.7
discount_rate=0.618

Epsilon=1.0
max_ep=1.0
min_ep=0.01
decay_rate=0.01


In [ ]:
# Epsilon Greedy Function
def ep_greedy_policy(Q, state):
  # create random  number between min and max value of E
  if (random.uniform(0,1) > Epsilon):
    #we need to exploit here
    return np.argmax(Q[state])
  else:
    #we need to explore here
    return env.action_space.sample()


*run Q-learning algo for all Total_episodes
initialise 
1.Target_Reached 
2.Current_steps
3.Enviroment
Reduce Epsilon formula is as follows :-*

    new_e = min_e + (max_e - min_e)*(2.71)^(-decay_rate*episodes)
    now iterate till max_steps_Limit
    Q(s,a) = Q(s,a) + learning_rate*( Reward(s,a) - discound_rate*Max(Q(s+1)) - Q(s+1))


  


In [ ]:
# training...
for i in range(0, Total_episodes):
  target_reached=False
  cur_step=0
  Prev_state = env.reset()
  Epsilon = min_ep + (max_ep - min_ep)*np.exp(-decay_rate*i)
  for j in range(0,Max_steps):
    action = ep_greedy_policy(Q, Prev_state)
    # order is : State, Reward, Target_Reached, Info
    new_state , reward, done, info = env.step(action)
    Q[Prev_state][action] = Q[Prev_state][action] + learning_rate*(reward + discount_rate*np.max(Q[Prev_state]) - Q[Prev_state][action])

    if(target_reached):break
    Prev_state = new_state


In [ ]:
# Test ... It will be displayed 100 times
Overall_reward=0
for attempt in range(0,1):
  prev_state = env.reset()
  cur_step=0
  Completed=False
  Game_Reward=0
  for steps in range(0, Max_steps):
    env.render()
    action = np.argmax(Q[prev_state])
    new_state, reward, Completed, info = env.step(action)
    Overall_reward+=reward
    Game_Reward+=reward
    if (Completed):
      # print("Your Score" , Game_Reward)
      break
    prev_state=new_state
env.close()
print("Average Score : " + str(Overall_reward/10.0))



+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: